node_id: 1
base_wal_dir: "./tmp/wal/deployd"
base_data_dir: "./tmp/data/deployd"
replica:
  storage:
    cluster:
      - http://storage1:21521
      - http://storage2:21522
      - http://storage3:21523
    bind_address: storage1:21521
    join: false
